# -*- coding: utf-8 -*-
"""Modified deephungarian with parameter changes 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Xbq6xxVewQl36rxxhrY4CaDCnVJ7fLQ

# Deep Speech with Common Voice data

First, check that you've got a usable GPU.
"""

import torch
torch.cuda.is_available()

"""Next install Coqui STT"""

!pip install -U pip
!pip install coqui_stt_training

"""For some reason, this doesn't seem to use the GPU and the following is necesssary."""

! pip uninstall tensorflow -y
! pip install "tensorflow-gpu==1.15.4"

"""Check that that worked:"""

!pip list | grep coqui

"""Mount your Google Drive"""

from google.colab import drive
drive.mount('/content/gdrive')

"""Check that that worked:"""

!ls

"""Check whether you have `My Drive` or `MyDrive`."""

!ls gdrive/

"""The system doesn't use the GPU unless all the data are copied over first. This can take a few minutes."""

!cp -r gdrive/MyDrive/SpeechTech/Hungarian/hu3/hu/ /content/

"""Copy the wav files that don't copy over because Google hates me"""

!cp -r gdrive/MyDrive/SpeechTech/Hungarian/wavs/* /content/hu/clips

"""Set parameters, build model, calculate alphabet. This can take a while."""

import coqui_stt_training
from coqui_stt_training.util.config \
	import initialize_globals_from_args
from coqui_stt_training.train import train
from coqui_stt_training.evaluate import test

#pfx ='/content/gdrive/MyDrive/hu/clips/'
pfx ='/content/hu/clips/'

initialize_globals_from_args(
	train_files=[pfx+"train.csv"],
	dev_files=[pfx+"dev.csv"],
	test_files=[pfx+"test.csv"],
	checkpoint_dir="hu3/hu/checkpoints/",
	load_train="init",
	n_hidden=100,
	epochs=25,
	beam_width=10,
	#train_batch_size=128,
	#dev_batch_size=128,
	#test_batch_size=10,
  train_batch_size=75,
  dev_batch_size=75,
  test_batch_size=10
)

"""Train:"""

train()

"""Copy best model back to Drive"""

cp -r hu3/hu/checkpoints gdrive/MyDrive/SpeechTech/Hungarian/hu3/check4

"""Test:"""

test()